---
tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -bn -i 4'
    format-stdin: true

  lua-format: &lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  python-yapf: &python-yapf
    format-command: 'yapf --quiet'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --quiet - '
    format-stdin: true

  html-prettier: &html-prettier
    format-command: 'prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser html'

  css-prettier: &css-prettier
    format-command: 'prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser css'

  scss-prettier: &scss-prettier
    format-command: 'prettier ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser scss'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  javascript-eslint: &javascript-eslint
    format-command: 'eslint_d -c ~/.config/eslint/eslintrc.yml -f unix --fix-to-stdout --stdin --stdin-filename ${INPUT}'
    format-stdin: true
    lint-command: 'eslint_d -c ~/.config/eslint/eslintrc.yml -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
  zsh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  lua:
    - <<: *lua-format

  yaml:
    - <<: *yaml-yamllint

  python:
    - <<: *python-yapf
    - <<: *python-isort

  html:
    - <<: *html-prettier

  htmldjango:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  scss:
    - <<: *scss-prettier

  javascript:
    - <<: *javascript-eslint
